[tool.black]
line-length = 120
target_version = ['py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | berkeleypoi/face_rec
    | berkeleypoi/hybrid
    | berkeleypoi/openface
    | berkeleypoi/test
    | berkeleypoi/util
    | common
    | devops
    | notebook
    | web
  )/
  | foo.py
)
'''